Resources:
  TODOAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
          IndexDocument: index.html
  TODOAppWebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref TODOAppBucket
      PolicyDocument: 
       Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
            Principal: '*'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${TODOAppBucket}/*'

Parameters:
  BucketName:
    Type: String
    Default: 'cloud-native-todo-app-2022' # Note that the name must be unique across all accounts
    MinLength: 3
    MaxLength: 63
    Description: Enter the bucket name for hosting the TODO app.
