Resources:
  TODOAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloud-native-todo-app-2022
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
          IndexDocument: index.html
  TODOAppWebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref TODOAppBucket
      PolicyDocument: 
       Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
            Principal: '*'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${TODOAppBucket}/*'
